# This is free and unencumbered software released into the public domain.

name: build

on:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

env:
  DUCKDB: 1.3.2
  ZIG: 0.15.1

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x64
            runner: ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: bash scripts/build.sh

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: duckdb-${{ env.ZIG }}-${{ env.DUCKDB }}-${{ matrix.arch }}
          path: lib/*.zip

      - name: Publish
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} lib/*.zip
